### ISSUE TITLE
Add Claude and Perplexity as Search Engines

### ISSUE THREAD

**Issue by sourceforge-editor** [matomo-org/searchengine-and-social-list#108]
I see ChatGPT was added to SearchEngines.yml a week or two ago. That's great. Could we add Perplexity and Claude to SearchEngines.yml in Matomo as well?
```yaml
  -
    urls:
      - claude.ai
    params: []
    hiddenkeyword:
      - '/^$/'

  -
    urls:
      - perplexity.ai
    params: []
    hiddenkeyword:
      - '/^$/'
```
